// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/bb7f67e2e1026054ab2d2d6d7c253a2478834d7d/md5/md5.d.ts
declare module 'md5' {
/**
 * js function for hashing messages with MD5
 * 
 * @param {(string | Buffer)} message - a string or buffer to hash
 * @returns {string} the resultant MD5 hash of the given message
 */
    function main(message: string | Buffer): string;
    export = main;
}