export declare class AgentDB {
    cid: string;
    apisys: string;
    apimicro: string;
    apiobj: string;
    agentname: string;
    description: string;
    maxcopy: number;
    version: string;
    errsec: number;
    state: string;
    lastheartbeat: Date | null;
    currentcopy: number;
    lastoktime: Date | null;
    lastokinfo: string;
    starttime: Date | null;
    endtime: Date | null;
    lasterrinfo: string;
    pricebase: number;
    price: number;
    costunit: number;
    profittarget: number;
    profittotal: number;
    costtotal: number;
    revenuetotal: number;
    roi: number;
    successcount: number;
    runcount: number;
    successrate: number;
    errorcount: number;
    costdescription: string;
    pricedescription: string;
    upby: string;
    uptime: Date | null;
    idpk: number | null;
    id: string | null;
    remark: string;
    remark2: string;
    remark3: string;
    remark4: string;
    remark5: string;
    remark6: string;
    jsobj: Record<string, any>;
    inputdata: Record<string, any>;
    outputdata: Record<string, any>;
    private handlersByType;
    private handlersByName;
    constructor(json_data?: Record<string, any>);
    setFromJson(json_data: Record<string, any>): this;
    toJson(): Record<string, any>;
    private loadHandlersFromJsonData;
    private convertHandlersToJsonArray;
    isActive(): boolean;
    addHandler(handler: any): void;
    getHandlerByCapability(type: string, capability: string): any | null;
    getHandlerByName(handlerName: string): any | null;
    getAllHandlersByType(): Map<string, Map<string, any>>;
    getAllHandlersByName(): Map<string, any>;
    getHandlersByType(type: string): Map<string, any> | null;
    executeHandler(handlerName: string, params: Record<string, any>): Promise<Record<string, any>>;
}
