export declare class Handler {
    cid: string;
    apiv: string;
    apisys: string;
    apiobj: string;
    idagent: string;
    idworkflow: string;
    handler: string;
    name: string;
    type: string;
    capability: string;
    description: string;
    state: string;
    pricebase: number;
    price: number;
    costunit: number;
    profittarget: number;
    profittotal: number;
    costtotal: number;
    revenuetotal: number;
    roi: number;
    successcount: number;
    runcount: number;
    successrate: number;
    errorcount: number;
    costdescription: string;
    pricedescription: string;
    upby: string;
    uptime: string | null;
    idpk: number | null;
    id: string | null;
    remark: string;
    remark2: string;
    remark3: string;
    remark4: string;
    remark5: string;
    remark6: string;
    callback?: (result: any, ...args: any[]) => Promise<any>;
    constructor(handlerData?: Partial<Handler>);
    setFromJson(json_data: Partial<Handler>): void;
    toJson(): Record<string, any>;
    isActive(): boolean;
    setCallback(callback: (result: any, ...args: any[]) => Promise<any>): void;
    executeCallback(result: any, ...args: any[]): Promise<any>;
    execute(params: any): Promise<any>;
}
