export declare class WorkflowDB {
    cid: string;
    uid: string;
    idworkflow: string;
    wfname: string;
    description: string;
    version: string;
    state: string;
    apisys: string;
    apimicro: string;
    apiobj: string;
    inputdata: string;
    outputdata: string;
    flowschema: string;
    starttask: string;
    starttime: string;
    endtime: string;
    lastoktime: string;
    errsec: string;
    progress: number;
    lasterrinfo: string;
    lastokinfo: string;
    max_concurrency: number;
    current_concurrency: number;
    retry_count: number;
    max_retries: number;
    total_tasks: number;
    completed_tasks: number;
    failed_tasks: number;
    totalcost: number;
    totalrevenue: number;
    totalprofit: number;
    roi: number;
    runcount: number;
    successcount: number;
    errorcount: number;
    successrate: number;
    executiontime: number;
    upby: string;
    uptime: string;
    idpk: number | null;
    id: string;
    remark: string;
    remark2: string;
    remark3: string;
    remark4: string;
    remark5: string;
    remark6: string;
    constructor(json_data?: Record<string, any>);
    set_from_json(json_data: Record<string, any>): this;
    get_from_json(): Record<string, any>;
    update_progress(completed: number, total: number): void;
}
